In [2]:
import numpy as np
print (np.version.version)

1.13.3


In [6]:
print (np.array([1,2,3,4]))

[1 2 3 4]


In [7]:
np.array([1.2,2,3,4])

array([ 1.2,  2. ,  3. ,  4. ])

In [10]:
type(np.array((1.2,3,2,4)))

numpy.ndarray

In [17]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [18]:
np.array((1.2,3,3,4),dtype=np.int32)

array([1, 3, 3, 4])

In [24]:
np.arange(15)
type(np.arange(15))
np.arange(15).reshape(3,5)
type(np.arange(15).reshape(3,5))

numpy.ndarray

In [25]:
np.linspace(1,3,9)

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [38]:
np.zeros((3,4))
np.ones((3,4))
np.eye((3))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [40]:
np.ones((3,4,2))

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [45]:
a = np.ones((3,4,2))
a.itemsize

8

In [51]:
a = np.array( [[2,3,4],[5,6,7]] )
a
a[1,2]
a[1,:]

a[1,1:2]

a[1,:] = [8,9,10]
a
# [[ 2  3  4]
#  [ 8  9 10]]

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [59]:
for x in np.linspace(1,4,4):
    print(x)

1.0
2.0
3.0
4.0


In [71]:
a = np.ones((2,2))
b = np.eye(2)
b>0
a-b
b*2
(a*2)*(b*2)-b+a/(b+1)
a**2

array([[ 1.,  1.],
       [ 1.,  1.]])

In [83]:
a.sum()
a.min()
a.max()
np.tan(a)
np.floor(a)
np.exp(a)
np.dot(a,a)


array([[ 2.,  2.],
       [ 2.,  2.]])

In [85]:
np.vstack((a,b))
np.hstack((a,b))

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.]])

In [96]:
c =np.hstack((a,b))
a[1,1]=1
# a[1,1]=20


array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.]])

In [113]:
a=np.ones((2,2))
b=a
b is a
a
c = a.copy()
c is a
a[1,1]=20
c


array([[ 1.,  1.],
       [ 1.,  1.]])

In [125]:
a =np.array([[1,2],[7,5]])
a.transpose()
a.T

array([[1, 7],
       [2, 5]])

In [126]:
np.trace(a)

6

In [128]:
import numpy.linalg as nplg
nplg.eig(a)

(array([-1.24264069,  7.24264069]), array([[-0.66557907, -0.30510159],
        [ 0.74632735, -0.95231981]]))