In [2]:
import numpy as np
import urllib.request
# url with dataset
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
# download the file
raw_data = urllib.request.urlopen(url)
# load the CSV file as a numpy matrix
dataset = np.loadtxt(raw_data, delimiter=",")
# separate the data from the target attributes
X = dataset[:,0:7]
y = dataset[:,8]
X

array([[   6.   ,  148.   ,   72.   , ...,    0.   ,   33.6  ,    0.627],
       [   1.   ,   85.   ,   66.   , ...,    0.   ,   26.6  ,    0.351],
       [   8.   ,  183.   ,   64.   , ...,    0.   ,   23.3  ,    0.672],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,  112.   ,   26.2  ,    0.245],
       [   1.   ,  126.   ,   60.   , ...,    0.   ,   30.1  ,    0.349],
       [   1.   ,   93.   ,   70.   , ...,    0.   ,   30.4  ,    0.315]])

In [3]:
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
             precision    recall  f1-score   support

        0.0       0.82      0.90      0.86       500
        1.0       0.77      0.63      0.69       268

avg / total       0.80      0.80      0.80       768

[[448  52]
 [ 98 170]]


## KNN效果不错，下面来继续距离KNN实战

In [122]:
#确保数据格式符合要求
#导入科学计算包（数组和矩阵）
from numpy import *
from os import listdir
#导入运算符模块
import operator

#创建符合python格式的数据集
def createDataSet():
    #数据集 list(列表形式）   
    group=array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    #标签
    labels=['A','A','B','B']
    return group, labels

### 对上面解释
1.from os import listdir导入文件夹文件（http://www.runoob.com/python/os-listdir.html） 。
2.import operator（http://blog.csdn.net/shengmingqijiquan/article/details/53005129）。

In [123]:
group,labels = createDataSet()
group

array([[ 1. ,  1.1],
       [ 1. ,  1. ],
       [ 0. ,  0. ],
       [ 0. ,  0.1]])

### 这是一篇不错的KNN实战讲解 讲解很详细  简单易懂

In [127]:
def classify0(inX,dataSet,labels,k):
    dataSetSize = dataSet.shape[0]
    #tile 扩展矩阵的函数
    diffMat = tile(inX,(dataSetSize,1))-dataSet
    sqdiffMat = diffMat**2
    sqDistances = sqdiffMat.sum(axis = 1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()
    print(sortedDistIndicies)
    classCount={}
    for i in range(k):
        voteLabels = labels[sortedDistIndicies[i]]
        #dict.get  获取指定键的值，默认返回none，键值不存在时，不同于dict['key']直接返回error，也可以指定，下面指定为0
        classCount[voteLabels] = classCount.get(voteLabels,0)+1
    print(classCount)
    #Python3.5中：iteritems变为items(python2   classCount.iteritems())
    #items可以输出dict中的（key，value）
    #sorted中的key参数传入函数，operator.itemgetterr函数获取的不是值，而是定义了一个函数，通过该函数作用到对象上才能获取值。
    #operator.itemgetter(1) 为获取classCount.items()中的第二个参数
    sortedClassCount = sorted(classCount.items(),key = operator.itemgetter(1),reverse = True)
    print(sortedClassCount)
    return sortedClassCount[0][0]

In [143]:
classify0([0,0.2],group,labels,2)

[3 2 1 0]
{'B': 2}
[('B', 2)]


'B'

### 深度解读一下上面这段代码

In [26]:
#argsort()函数是将x中的元素从小到大排列，提取其对应的index(索引)，然后输出到y。
#输出是按照从小到大的顺序输出的
import numpy as np
a=np.array([2,3,1,4,5,6,7,0,2])
a.argsort()

array([7, 2, 0, 8, 1, 3, 4, 5, 6], dtype=int64)

In [39]:
#dict.get vs dict[‘key’]
a={'name':'abeltowne'}
a['name']

'abeltowne'

In [40]:
#Python中sort 和 sorted函数
#用sort函数对列表排序时会影响列表本身，而sorted不会
a = [1,2,1,4,3,5]
a.sort()
a

[1, 1, 2, 3, 4, 5]

In [45]:
a = [1,2,1,4,3,5]
b =sorted(a)
a

[1, 2, 1, 4, 3, 5]

In [53]:
list1 = [('david', 90), ('mary',90), ('sara',80),('lily',95)]
sorted(list1,key = lambda list1:list1[0])

[('david', 90), ('lily', 95), ('mary', 90), ('sara', 80)]

In [55]:
# list1[0],list1[1]标示第一第二个元素
list1 = [('david', 90), ('mary',90), ('sara',80),('lily',95)]
sorted(list1,key = lambda list1:list1[1])

[('sara', 80), ('david', 90), ('mary', 90), ('lily', 95)]

In [60]:
#python tile函数(https://www.cnblogs.com/zibu1234/p/4210521.html) 即重复A B次
np.tile([1,2],(2,3))

array([[1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2]])

In [68]:
diffM = tile([0,0.3],(4,1))-group
diffM**2
#**2标示 每个元素自乘2 即平方

array([[ 1.  ,  0.64],
       [ 1.  ,  0.49],
       [ 0.  ,  0.09],
       [ 0.  ,  0.04]])

In [87]:
#python 中的循环
k=5
for i in range(k):
    print(i)
#输出的是0到k-1

0
1
2
3
4


In [166]:
##operator.itemgetter()
a = [['a',1],['b',4],['c',5]]
sorted(a,key = operator.itemgetter(0),reverse = True)


[['c', 5], ['b', 4], ['a', 1]]